previewsEnabled: true
services:
  # A Docker web service
  - type: web
    name: ia-boe
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.service.main:app --host 0.0.0.0 --port 10000 --workers 1 --timeout-keep-alive 125 --log-level info
