services:
  # A Docker web service
  - type: web
    name: ia-boe
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.service.main:APP --host 0.0.0.0 --port $PORT --workers 2 --timeout-keep-alive 125 --log-level error
