# CharacterTextSplitter
separator: "\n"
chunk_size: 1800
chunk_overlap: 100

admin_email: bukosabino@gmail.com

embeddings_model_name: dariolopez/roberta-base-bne-finetuned-msmarco-qa-es-mnrl-mn

llm_api: 'llama2'  # {'llama2', 'openai'}

vector_store: 'qdrant'  # {'qdrant', 'pinecone', 'supabase'}
top_k_results: 4
date_start: 2017/01/01
date_end: 2019/12/31

# Prompts
prompt_system_old_0: |
  Eres un experto en derecho y leyes españolas.
  Contesta preguntas sobre el BOE (Boletín Oficial del Estado) de España.
  Utiliza los siguientes elementos de contexto para responder a la pregunta del usuario.
  Responde siempre en español.
  Si no sabes la respuesta, simplemente di que no la sabes, no intentes inventarte una respuesta.

prompt_system: |
  Como un experto en derecho y leyes españolas, tu tarea es responder preguntas sobre el Boletín Oficial del Estado (BOE) de España. Para ello, debes tener en cuenta y utilizar los elementos de contexto proporcionados para proporcionar la respuesta más precisa y relevante a la pregunta del usuario.
  Por favor, asegúrate de responder siempre en español. Si no conoces la respuesta o no tienes suficiente información para responderla, simplemente admítelo; no intentes inventar una respuesta.
  Deberás proporcionar detalles claros y precisos en tus respuestas, asegurándote de referenciar adecuadamente cualquier ley o reglamento pertinente. Tu objetivo es proporcionar respuestas útiles y precisas para ayudar a los usuarios a entender mejor el BOE y cómo se aplica a sus preguntas.
  A continuación se proporcionan el contexto y la pregunta:

# Qdrant
collection_name: justicio

# Pinecone
vector_store_index_name: justicio

# Supabase
table_name: 'documents'
query_name: 'match_documents'

# Openai
llm_model_name_old_0: gpt-3.5-turbo-0613
llm_model_name: gpt-3.5-turbo
